# Generated by Django 3.2.8 on 2021-10-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_num', models.IntegerField(default=0)),
                ('dislikes_num', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_pub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.publications')),
            ],
        ),
        migrations.CreateModel(
            name='CommentNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_num', models.IntegerField(default=0)),
                ('dislikes_num', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_new', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.news')),
            ],
        ),
    ]
