# Generated by Django 3.2.8 on 2021-10-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_commentnews_commentpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='dislikes_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publications',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
    ]
